### ISSUE TITLE
Feature Request: authentication with password

### ISSUE THREAD

**Issue by Sparklet73** [travelstart/hapi-db-manager#21]
Since db manager should only be accessed by the validated user, I consider adding authentication on it.
The first phase will add a field like `password` to db config and use `yar` module to support session. Then implement a plugin to fit this authentication. (plugin may refer to [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie))
After that will added verify token route to the api which will be called before every request.

**Comment by starlightslo** [comment]
I modified the plugin options, please check as below:

### Plugin Options

* `managerPath`: (string) The route path for database manager web. - default: `/dbadmin`
* `databaseConfigList`:
  * `name`: (string) The name of database for display.
  * `client`: (string) Client adapter. [`sqlite3`, `pg`, `mysql`]
  * `connection`: (Object) Reference [Knex](http://knexjs.org/#Installation-client).
  * `pool`: (string) Reference [Knex](http://knexjs.org/#Installation-client).
  * `useNullAsDefault`: (boolean) If you are using sqlite3, please set `True`.
* `debug`: (boolean) Not supported yet.
* `auth`: (string) This defines which authentication will be used. - default: `local-password` [`local-password`]
* `password`: (string) This option only available when auth is `local-password`, no auth required if the value is empty.

**Comment by starlightslo** [comment]
#22

**Comment by starlightslo** [comment]
#22
